import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { UserProvider } from './context/UserContext';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <UserProvider>
          <Navbar />
          <Toaster position="top-centercd" />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
